plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-hacker

title: md2htmljekyll
description: md2htmljekyll test {{ 'now' | date: "%Y-%m-%d %H:%M:%S %Z" }}
